@startuml
title Load Controller - Sequence diagram UML

participant Controller
participant ControllerManager
participant ControllerFactory
participant Frame
participant StaffController
participant AbsView

activate Controller

Controller -> ControllerManager: getInstance().loadController(TypeController t)

activate ControllerManager


ControllerManager -> ControllerFactory:  ControllerFactory.createController()
activate ControllerFactory
ControllerFactory --> ControllerManager
deactivate ControllerFactory

ControllerManager -> StaffController: StaffController.inizialize()
activate StaffController

StaffController -> AbsView: new AbsView()
activate AbsView
AbsView --> StaffController
deactivate AbsView
StaffController --> ControllerManager
deactivate StaffController 

ControllerManager -> StaffController: getView()
activate StaffController
StaffController --> ControllerManager
deactivate StaffController 

ControllerManager -> Frame: loadView()
activate Frame
Frame --> ControllerManager
deactivate Frame

deactivate ControllerManager
deactivate Controller

@enduml
