@startuml
title AddComponent - Sequence diagram UML

actor Mechanic

participant Login
participant MechanicHome
participant AddComponent
participant RemoveComponent

Mechanic -> Login : log as mechanic

activate Login
Login -> MechanicHome : carica la home del meccanico
deactivate Login

activate MechanicHome
MechanicHome -> MechanicHome : inserisce una vettura

MechanicHome -> AddComponent : seleziona add component

deactivate MechanicHome
activate AddComponent

alt wear < 50
    AddComponent -> RemoveComponent
    activate RemoveComponent
    RemoveComponent --> AddComponent
    deactivate RemoveComponent
end

AddComponent --> MechanicHome
deactivate AddComponent
activate MechanicHome

@enduml