use database_scuderia;

insert into staff (ID, PASSWORD, ROLE)
values
('01MM', 'MMpwd123','Mechanic'),
('01MR', 'MRpwd123','Strategist'),
('01RC', 'RCpwd123','Warehouseman'),
('02LB', 'LBpwd456','Strategist'),
('02SC', 'SCpwd456','Mechanic');

insert into pilot(ID, NAME, SURNAME, NUMBER)
values
(1,'CARLO','LECLERCO',61),
(2,'LUIGI','AMILTONE',8);

insert into vehicle(MSN, TIME_SECTOR1, TIME_SECTOR2, TIME_SECTOR3, ID_PILOT, ID_MECHANIC, ID_STRATEGIST)
values
('SF24-001',NULL, NULL, NULL, NULL, NULL, NULL),
('SF24-002',NULL, NULL, NULL, NULL, NULL, NULL);

insert into component(NAME, WEAR, STATUS, WAREHOUSE, ID_VEHICLE)
values
('RUOTA ANTERIORE SX HARD', 100, 'NEW', TRUE, NULL),
('RUOTA ANTERIORE SX HARD', 100, 'NEW', TRUE, NULL),
('RUOTA ANTERIORE SX HARD', 100, 'NEW', TRUE, NULL),
('RUOTA ANTERIORE SX HARD', 100, 'NEW', TRUE, NULL),

('RUOTA ANTERIORE DX HARD', 100, 'NEW', TRUE, NULL),
('RUOTA ANTERIORE DX HARD', 100, 'NEW', TRUE, NULL),
('RUOTA ANTERIORE DX HARD', 100, 'NEW', TRUE, NULL),
('RUOTA ANTERIORE DX HARD', 100, 'NEW', TRUE, NULL),

('RUOTA POSTERIORE SX HARD', 100, 'NEW', TRUE, NULL),
('RUOTA POSTERIORE SX HARD', 100, 'NEW', TRUE, NULL),
('RUOTA POSTERIORE SX HARD', 100, 'NEW', TRUE, NULL),
('RUOTA POSTERIORE SX HARD', 100, 'NEW', TRUE, NULL),

('RUOTA POSTERIORE DX HARD', 100, 'NEW', TRUE, NULL),
('RUOTA POSTERIORE DX HARD', 100, 'NEW', TRUE, NULL),
('RUOTA POSTERIORE DX HARD', 100, 'NEW', TRUE, NULL),
('RUOTA POSTERIORE DX HARD', 100, 'NEW', TRUE, NULL),

('RUOTA ANTERIORE SX MEDIUM', 100, 'NEW', TRUE, NULL),
('RUOTA ANTERIORE SX MEDIUM', 100, 'NEW', TRUE, NULL),
('RUOTA ANTERIORE SX MEDIUM', 100, 'NEW', TRUE, NULL),
('RUOTA ANTERIORE SX MEDIUM', 100, 'NEW', TRUE, NULL),

('RUOTA ANTERIORE DX MEDIUM', 100, 'NEW', TRUE, NULL),
('RUOTA ANTERIORE DX MEDIUM', 100, 'NEW', TRUE, NULL),
('RUOTA ANTERIORE DX MEDIUM', 100, 'NEW', TRUE, NULL),
('RUOTA ANTERIORE DX MEDIUM', 100, 'NEW', TRUE, NULL),

('RUOTA POSTERIORE SX MEDIUM', 100, 'NEW', TRUE, NULL),
('RUOTA POSTERIORE SX MEDIUM', 100, 'NEW', TRUE, NULL),
('RUOTA POSTERIORE SX MEDIUM', 100, 'NEW', TRUE, NULL),
('RUOTA POSTERIORE SX MEDIUM', 100, 'NEW', TRUE, NULL),

('RUOTA POSTERIORE DX MEDIUM', 100, 'NEW', TRUE, NULL),
('RUOTA POSTERIORE DX MEDIUM', 100, 'NEW', TRUE, NULL),
('RUOTA POSTERIORE DX MEDIUM', 100, 'NEW', TRUE, NULL),
('RUOTA POSTERIORE DX MEDIUM', 100, 'NEW', TRUE, NULL),

('ALA ANTERIORE', 100, 'NEW', TRUE, NULL),
('ALA ANTERIORE', 100, 'NEW', TRUE, NULL),
('ALA ANTERIORE', 100, 'NEW', TRUE, NULL),
('ALA ANTERIORE', 100, 'NEW', TRUE, NULL),

('DRS', 100, 'NEW', TRUE, NULL),
('DRS', 100, 'NEW', TRUE, NULL),
('DRS', 100, 'NEW', TRUE, NULL),
('DRS', 100, 'NEW', TRUE, NULL),

('MOTORE TERMICO', 100, 'NEW', TRUE, NULL),
('MOTORE TERMICO', 100, 'NEW', TRUE, NULL),
('MOTORE TERMICO', 100, 'NEW', TRUE, NULL),
('MOTORE TERMICO', 100, 'NEW', TRUE, NULL),

('ERS', 100, 'NEW', TRUE, NULL),
('ERS', 100, 'NEW', TRUE, NULL),
('ERS', 100, 'NEW', TRUE, NULL),
('ERS', 100, 'NEW', TRUE, NULL);
