CREATE TABLE STAFF (
    ID CHAR(128) PRIMARY KEY,      
    PASSWORD CHAR(128) NOT NULL,         
    ROLE ENUM('Strategist', 'Mechanic', 'Warehouseman') NOT NULL,
    NAME VARCHAR(128) NOT NULL,
    SURNAME VARCHAR(128) NOT NULL 
);

CREATE TABLE PILOT (
    ID INT PRIMARY KEY,
    NAME CHAR(128) NOT NULL,
    SURNAME CHAR(128) NOT NULL,
    NUMBER INT NOT NULL
);

CREATE TABLE VEHICLE (
    MSN CHAR(128) PRIMARY KEY,
    TIME_SECTOR1 LONG,
    TIME_SECTOR2 LONG,
    TIME_SECTOR3 LONG,
    ID_PILOT INT,
    ID_MECHANIC CHAR(128),
    ID_STRATEGIST CHAR(128),

    FOREIGN KEY (ID_PILOT) REFERENCES PILOT(ID),
    FOREIGN KEY (ID_MECHANIC) REFERENCES STAFF(ID),
    FOREIGN KEY (ID_STRATEGIST) REFERENCES STAFF(ID)
);

CREATE TABLE COMPONENT (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME CHAR(128) NOT NULL,
    WEAR INT,
    STATUS CHAR(128),
    WAREHOUSE BOOLEAN,
    ID_VEHICLE CHAR(128),

    FOREIGN KEY (ID_VEHICLE) REFERENCES VEHICLE(MSN)
);

CREATE TABLE REQUEST (
    ID INT,
    ID_MECHANIC CHAR(128),
    ID_COMPONENT INT,                      
    ID_VEHICLE CHAR(128), 
    DESCRIPTION TEXT NOT NULL,
    
    PRIMARY KEY (ID, ID_MECHANIC, ID_COMPONENT, ID_VEHICLE),
    
    FOREIGN KEY (ID_VEHICLE) REFERENCES VEHICLE(MSN),
    FOREIGN KEY (ID_MECHANIC) REFERENCES STAFF(ID),
    FOREIGN KEY (ID_COMPONENT) REFERENCES COMPONENT(ID)                 
);

CREATE TABLE LOG_EVENT (
    ID CHAR(128) PRIMARY KEY AUTO_INCREMENT,
    ID_STAFF CHAR(128),
    DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DESCRIPTION TEXT NOT NULL,

    FOREIGN KEY (ID_STAFF) REFERENCES STAFF(ID) 
);