
create schema if not exists database_scuderia charset utf16;

use database_scuderia;

CREATE TABLE PILOT (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME CHAR(128) NOT NULL,
    SURNAME CHAR(128) NOT NULL,
    NUMBER INT NOT NULL
);

CREATE TABLE STAFF (
    ID CHAR(128) PRIMARY KEY,     
    NAME CHAR(128) NOT NULL,            
    SURNAME CHAR(128) NOT NULL,        
    PASSWORD CHAR(128) NOT NULL,         
    ROLE ENUM('Stratega', 'Meccanico', 'Magazziniere') NOT NULL,  
    ID_VEHICLE CHAR,                        
    

    FOREIGN KEY (ID_VEHICLE) REFERENCES VEHICLE(MSN)  
);

CREATE TABLE REQUEST (
    ID INT PRIMARY KEY AUTO_INCREMENT,    
    DESCRIPTION TEXT NOT NULL,           
    ID_STAFF CHAR(128),                        
    ID_COMPONENT INT,                     
    ID_VEHICLE CHAR(128),                       

    FOREIGN KEY (ID_STAFF) REFERENCES Staff(ID),          
    FOREIGN KEY (ID_COMPONENT) REFERENCES Component(ID), 
    FOREIGN KEY (ID_VEHICLE) REFERENCES VEHICLE(MSN)        
);

CREATE TABLE VEHICLE (
    MSN CHAR(128) PRIMARY KEY,
    TIME_SECTOR1 LONG,
    TIME_SECTOR2 LONG,
    TIME_SECTOR3 LONG,
    ID_PILOT INT,

    FOREIGN KEY (ID_PILOT) REFERENCES PILOT(ID)
);

CREATE TABLE COMPONENT(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME CHAR(128) NOT NULL,
    WEAR INT,
    STATUS CHAR(128),
    WAREHOUSE BOOLEAN
    ID_VEHICLE CHAR(128),

     FOREIGN KEY (ID_VEHICLE) REFERENCES VEHICLE(MSN)
);