@startuml

skinparam dpi 1000

scale max 720 width

top to bottom direction

title Gestione Scuderia

skinparam DefaultFontName Consolas

package controller {
  abstract class AbsController {
    # view : AbsView
    + {abstract} void initialize()
    + {abstract} AbsController.Type getType()
    + AbsView getView()
    + void onLoad()
  }

  enum AbsTypeController {
    LOGIN
    STRATEGA
    MECCANICO
    MAGAZZINIERE
  }

  class ControllerFactory{
    + {static}AbsController createController(AbsController.TypeController type)
  }

  class ControllerManager << (S,Violet) singleton >> {
    - instance : ControllerManager
    - frame : Frame
    - currentController : AbsController
    + {static} ControllerManager getInstance()
    + void loadController(AbsController.Type c)
    + void closeWindow()
  }
  
  class LoginController{
    - logv : LoginView
    - void accedi()
    - char[] getPassword()
    - String getUsername()
    + TypeController getType()
    + void initialize()
    + onLoad()
  }

  class MagazziniereController{
    - m : Magazziniere
    - obs : Observable
    - user : Staff
    - String getID()
    + TypeController getType()
    + void initialize()
    + void onLoad()  
  }

  class McGraphicAllComponentHandler{
    - components : Set<Components> 
    - gv : McGraphicAllComponentView
    - Set<Components> fetchComponent()
    + void showWindow()
  }
  
  class McGraphicTimePsHandler{
    - labelTim : ArrayList<String>
    - anomalyLabelTime : ArrayList<String>
    - gtpv : McGraphicTimePsView
    - String convertTime(int millis)
    - ArrayList<Integer> fetchTimePitStop()
    + void initialize()
    + void showWindow() 
  }

  class McPopUpComponentHandler{
    - pc : McPopUpComponentView
    - pr : McPopUpRequestView
    - md : MeccanicoDAO
    - c  : Components
    - int addCompo()
    - String fetchMSN()
    - String getID()
    + McPopUpComponentHandler()
    + void clear()
    + void showWindow()
  }

  class McPopUpPilotHandler{
    - pv : McPopUpPilotView 
    - md : MeccanicoDAO
    - String fetchMSN()
    - String getID()
    + McPopUpPilotHandler(MeccanicoView mv)
    + void clear()
    + void showWindow()

  }

  class McPopUpRequestHandler {
    - pr : McPopUpRequestView 
    - md : MeccanicoDAO 
    - String fetchMSN() 
    - String getID()
    + McPopUpRequestHandler()
    + void clear()
    + void showWindow()
  }

 class McPopUpVehicleHandler{
    - vv : McPopUpVehicleView 
    - md : MeccanicoDAO 
    - Vehicle addVehicle()
    - String getID()
    + McPopUpVehicleHandler(MeccanicoView mv)
    + void showWindow()
    + void clear() 
 }
 
  class MeccanicoController{
    - user : Staff 
    - m : Meccanico
    - boolean getComponent()
    - String getID()
    + TypeController getType()
    + void initialize()
    + void onLoad()
  }
  
  class Observable{
    - observers : List<Observer>
    + void addObserver(Observer observer)
    + void removeObserver(Observer observer)
    + void notifyObservers(int totalRequests)
  }

  class Observer << (I,BLUE) Observer >> {
    + void update(int totalRequest)
  }
 
  class StPopUpCreateStrategyHandler {
    - pcs : StPopUpCreateStrategyView 
    - gdv : StGraphicDetailsView 
    - sd : StrategistDAO 
    - setPoint : int 
    - average : int
    - Set<Components> getComponent()
    - int getComponentSize()
    - String getID()
    + StPopUpCreateStrategyHandler(int rc, int tmeLap)
    + void showWindow()
  }
 
  class StrategistController{
    - user : Staff 
    - st : Stratega 
    - minT1 : int 
    - minT2 : int 
    - minT3 : int 
    - timeLap : int 
    - String convertTime(int millis)
    - int getTimeLap()
    - Vehicle getVehicle()
    - void setTimeLap()
    + void createTable(StrategistView sv)
    + TypeController getType() 
    + void initialize()
  }
 
  class WhPopUpDeleteRequestHandler{
    - pdr : WhPopUpDeleteRequestView 
    - md : MagazziniereDAO
    - int setTotalRequest()
    - String getID()
    + WhPopUpDeleteRequestHandler(Observable observable)
    + void clear()
    + void showWindow()
  }
 
  class WhPopUpShowRequestHandler{
    - WhPopUpShowRequestView psr
    - Set<Request> getRequest()
    + void showWindow()
  }

  class WhPopUpUpdateComponentHandler {
    - puc : WhPopUpUpdateComponentView 
    - md : MagazziniereDAO
    - String getID()
    + WhPopUpUpdateComponentHandler()
    + void showWindow()
  }

 ControllerManager --o AbsController
 ControllerManager -- ControllerFactory  


 LoginController -up-|> AbsController
 MeccanicoController -up-|> AbsController
 MagazziniereController -up-|> AbsController

 StrategistController -up-|> AbsController

 MeccanicoController --o McGraphicAllComponentHandler
 MeccanicoController --o McGraphicTimePsHandler
 MeccanicoController --o McPopUpComponentHandler
 MeccanicoController --o McPopUpPilotHandler
 MeccanicoController --o McPopUpRequestHandler
 MeccanicoController --o McPopUpVehicleHandler
 
 MagazziniereController --o WhPopUpDeleteRequestHandler
 MagazziniereController --o WhPopUpShowRequestHandler
 MagazziniereController --o WhPopUpUpdateComponentHandler
 
 StrategistController --o StPopUpCreateStrategyHandler

 AbsController -up-* AbsTypeController
 AbsController -right-o ControllerFactory
 ControllerManager -left-* AbsTypeController
 MagazziniereController -- Observable
 Observable -- Observer 

}

package model.staff{
  class Magazziniere{
    - request : Set<Request>
    + TypeController getType()
    + Set<Request> getRequest()
    + void setRequest(Set<Request> request)
    + int totalRequest()
  }
 
  class Meccanico{
    - MSN : String 
    - vehicles : Vehicle 
    - allTimePitStop : ArrayList<Integer> 
    - anomalyTime : ArrayList<Integer>
    - void checkPS(int timePS)
    + Meccanico(String id, String pwd)
    + int addComponent(Vehicle v, Components c)
    + Vehicle addVehicle()
    + double convertTime(String tps)
    + ArrayList<Integer> getAllTimePitStop()
    + ArrayList<Integer> getAnomalyTime()
    + String getMSN()
    + TypeController getType()
    + Vehicle getVehicles()
    + void removeComponent(Vehicle v, Components c)
    + void setAllTimePitStop(ArrayList<Integer> allTimePitStop)
    + void setAnomalyTime(ArrayList<Integer> anomalyTime)
    + void setMSN(String mSN)
    + int setTimePS()
    + void setVehicles(Vehicle vehicles) 
  }
  
  class Session << (S,Violet) singleton >> {
    - operation : String 
    - strategy : String  
    - id_pilot : String  
    - id_staff : String 
    - pwd_staff : String 
    - mgd : MagazziniereDAO 
    - name : String  
    - surname : String 
    - m : Meccanico 
    - wh : Magazziniere 
    - s : Stratega 
    - v : Vehicle 
    - Session()
    + Staff getCurrentUser()
    + void setCurrentUser(Staff user)
    + String getOperation()
    + void setOperation(String operation)
    + String getId_pilot()
    + void setId_pilot(String id_pilot)
    + String getId_staff()
    + void setId_staff(String id_staff)
    + String getPwd_staff()
    + void setPwd_staff(String pwd_staff)
    + String getName()
    + void setName(String name)
    + String getSurname()
    + void setSurname(String surname)
    + void getTps()
    + void getRequest()
    + void getTS()
    + Vehicle getV()
    + void setV(Vehicle v)
    + Meccanico getM()
    + void setM(Meccanico m)
    + Magazziniere getWh()
    + void setWh(Magazziniere wh)
    + Stratega getS()
    + void setS(Stratega s)
    + String getStrategy()
    + void setStrategy(String strategy)
  }

  abstract class Staff{
    - id : String 
    - password : String 
    + Staff(String id, String pwd )
    + void checkValidity()
    + String getID()
    + String getPwd()
    + {abstract} TypeController getType()
    + {static} checkId void checkID(String id)
  }
  
  enum StaffTypeController {
    STRATEGA
    MECCANICO
    MAGAZZINIERE
  }
  
  class Stratega{
    - timeLap : int 
    + Stratega(String id, String pwd)
    + TypeController getType()
    + int getTimeLap()
    + void setTimeLap(int timeLap)
  }
   
 Staff -* StaffTypeController

}

package model.vehicle{
  class Vehicle{
    - component : Set<Components> 
    - MSN : String 
    - timeLap : String 
    - timeSect1 : int 
    - timeSect2 :  int 
    - timeSect3 : int
    + Vehicle(String MSN)
    + int addComponent(Components cmp)
    + Set<Components> getComponent()
    + void getComponentByName(String name)
    + String getMSN()
    + String getTimeLap() 
    + int getTimeSect1() 
    + int getTimeSect2()
    + int getTimeSect3()
    + void removeComponent(Components cmp)
    + void setComponents(Set<Components> component)
    + void setMSN(String mSN)
    + void setTimeSect()
  }
}

package model.request{
  class Request{
    - description : String 
    - id_s : String 
    - id_v : String 
    - id_r : int 
    - id_c : int 
    + int getId_r()
    + void setId_r(int id_r)
    + String getDescription()
    + void setDescription(String description)
    + String getId_s()
    + void setId_s(String id_s)
    + int getId_c()
    + void setId_c(int id_c)
    + String getId_v()
    + void setId_v(String id_v)
 }
}

package model.pilot{
  class Pilot{
    - id_pilot : String 
    - name : String 
    - surname : String 
    - number : int 
    + Pilota(String id_pilot, String name, String surname, int number)
    + String getId_pilot()
    + void setId_pilot(String id_pilot)
    + String getName()
    + void setName(String name)
    + String getSurname()
    + void setSurname(String surname)
    + int getNumber()
    + void setNumber(int number)
 }
}

package model.component{
  class Components{
    - idComponent : int 
    - name : String 
    - replacementStatus : String
    + Components(int id_c,String name)
    + int calculateWear(String replacementStatus)
    + int getIdComponent() 
    + void setIdComponent(int idComponent)
    + String getName()
    + void setName(String name)
    + String getReplacementStatus() 
    + void setReplacementStatus(String replacementStatus)
    + int getWear()
    + void setWear(int wear)
  }
}

 Meccanico -up-|> Staff
 Magazziniere -up-|> Staff
 Stratega -up-|> Staff

 Session -- Meccanico
 Session -- Magazziniere
 Session -- Stratega
 Session -- Vehicle

 Session -.. MeccanicoController
 Session -.. MagazziniereController
 Session -.. StrategistController

 Staff -- MeccanicoController
 Staff -- MagazziniereController
 Staff -- StrategistController

 Session -.. LoginController
 Session -.. McGraphicAllComponentHandler
 Session -.. McGraphicTimePsHandler
 Session -.. McPopUpComponentHandler
 Session -.. McPopUpPilotHandler
 Session -.. McPopUpRequestHandler
 Session -.. McPopUpVehicleHandler 
 Session -.. StPopUpCreateStrategyHandler
 Session -.. WhPopUpDeleteRequestHandler
 Session -.. WhPopUpShowRequestHandler
 Session -.. WhPopUpUpdateComponentHandler

 Meccanico -- MeccanicoController 
 Magazziniere -- MagazziniereController 
 Stratega -- StrategistController
 Meccanico -- Vehicle
 Vehicle -- Components
 Magazziniere -- Request

 McGraphicAllComponentHandler -- Components
 McPopUpComponentHandler -- Components

package view{
  abstract class AbsView{
    + void onLoad()
  }

  class LoginView{
    - mainContainer : JPanel 
    - logoPanel : JPanel
    - loginPanel : JPanel
    - btnPanel : JPanel
    - errorPanel : JPanel
    - username : JTextField
    - pwd : JPasswordField
    - imgBackgroundLabel : JLabel 
    - imgLogoLabel : JLabel
    - errLabel : JLabel
    - loginBtn : JButton
    - imgBackground : ImageIcon 
    - imgLogo :  ImageIcon
    + LoginView()
    + JButton getAccediButton()
    + JPasswordField getPasswordField()
    + JTextField getUsernameField()
    + void onLoad()
    + void upError()
  }

  class MagazziniereView{
    - frame : JFrame
    - mainContainer : JPanel  
    - titlePanel : JPanel
    - popUpPanel : JPanel
    - mexPanel : JPanel
    - showRequestButton : JButton
    - deleteRequestButton : JButton
    - updateCompoButton : JButton
    - comboBox : JComboBox<String>
    - imgLabel : JLabel
    - dataLabel : JLabel
    - mex : JLabel
    - imgUser : ImageIcon
    - imgWllp2 : ImageIcon
    - placeholder : JTextField
    - totalRequests : int
    - name : String
    - surname : String
    - void refresh(String name, String surname, int totalRequests)
    + JButton getShowRequestButton()
    + JButton getDeleteRequestButton() 
    + JButton getUpdateCompoButton()
    + JComboBox<String> getCombobox()
    + void setMex()
    + void data(String name, String surname, int totalRequests)
    + void mexCombo(int quantity)
  }

  class McGraphicAllComponentView{
    - frame : JFrame
    - mainPanel : JPanel 
    - panel : JScrollPane 
    - table : JTable
    + McGraphicAllComponentView(Set<Components> components)
    + void show() 
  }

  class McGraphicTimePsView{
    - width : int 
    - height : int 
    - padding : int 
    - labelPadding : int 
    - lineColor : Color 
    - pointColor : Color 
    - gridColor : Color 
    - GRAPH_STROKE : {static} Stroke 
    - pointWidth : int 
    - numberYDivisions : int 
    - scores : ArrayList<Integer>  
    - frame :JFrame  
    - messageLabel : JLabel 
    - tmeLabel : JLabel
    - messagePanel :  JPanel
    - double getMaxScore() 
    - double getMinScore()
    + McGraphicTimePsView(ArrayList<Integer> scores, ArrayList<String> labelTime)
    + void anomalyTime(ArrayList<String> at)
    + void show()
  }

  class McPopUpComponentView{
    - frame : JFrame
    - dataPanel : JPanel 
    - sendPanel : JPanel
    - titleLabel : JLabel 
    - mexLabel : JLabel
    - idC : JTextField 
    - nameC : JTextField
    - statusC : JTextField
    - sendButton : JButton
    + McPopUpComponentView()
    + void clearComponents(JPanel panel)
    + JPanel getDataPanel()
    + JTextField getIdC() 
    + void setIdC(JTextField insertID_C)
    + JTextField getNameC()
    + void setNameC(JTextField nameC)
    + JTextField getStatusC() 
    + void setStatusC(JTextField statusC)
    + JButton getSendButton()
    + void setSendButton(JButton sendButton)
  }

  class McPopUpPilotView{
    - frame : JFrame
    - dataPanel : JPanel 
    - sendPanel : JPanel
    - titleLabel : JLabel 
    - mexLabel : JLabel 
    - id : JTextField
    - name : JTextField
    - surname : JTextField 
    - number : JTextField
    - sendButton : JButton
    + McPopUpPilotView()
    + void clearComponents(JPanel panel)
    + JTextField getId()
    + void setId(JTextField id)
    + void setName(JTextField name)
    + JTextField getSurname()
    + void setSurname(JTextField surname)
    + JTextField getNumber()
    + void setNumber(JTextField number)
    + JButton getSendButton()
    + void setSendButton(JButton sendButton)
    + JPanel getDataPanel()
    + void setDataPanel(JPanel dataPanel)
    + JPanel getSendPanel()
    + void setSendPanel(JPanel sendPanel) 
  }

  class McPopUpRequestView{
    - frame : JFrame
    - dataPanel : JPanel 
    - sendPanel : JPanel
    - titleLabel : JLabel 
    - mexLabel : JLabel 
    - id_s : JTextField
    - id_c : JTextField
    - id_v : JTextField 
    - desc : JTextArea
    - sendButton : JButton
    + McPopUpRequestView()
    + void clearComponents(JPanel panel)
    + JPanel getDataPanel()
    + void setDataPanel(JPanel dataPanel)
    + JTextField getId_s()
    + void setId_s(JTextField id_s)
    + JTextField getId_c()
    + void setId_c(JTextField id_c) 
    + JTextField getId_v()
    + void setId_v(JTextField id_v) 
    + JTextArea getDesc()
    + void setDesc(JTextArea desc) 
    + JButton getSendButton()
    + void setSendButton(JButton sendButton)
    + JPanel getSendPanel()
    + void setSendPanel(JPanel sendPanel)
    + void show()
    + void mex() 
    + void mex1() 
    + void hide()
    + void title() 
  }

  class McPopUpVehicleView{
    - frame : JFrame
    - dataPanel : JPanel 
    - sendPanel : JPanel
    - titleLabel : JLabel 
    - mexLabel : JLabel 
    - msn : JTextField
    - id_p : JTextField
    - sendButton : JButton
    + McPopUpVehicleView()
    + void clearComponents(JPanel panel)
    + void close()
    + JPanel getDataPanel()
    + JTextField getId_p()
    + JTextField getMsn()
    + JButton getSendButton()
    + JPanel getSendPanel() 
    + void mex()
    + void setDataPanel(JPanel dataPanel)
    + void setId_p(JTextField id_p) 
    + void setMsn(JTextField msn)
    + void setSendButton(JButton sendButton)
    + void setSendPanel(JPanel sendPanel)
    + void show() 
  }

  class MeccanicoView{
    - frame : JFrame
    - mainContainer : JPanel 
    - popUpPanel : JPanel
    - grapichPanel : JPanel 
    - overlayPanel : JLayeredPane
    - imgLabel : JLabel 
    - mex : JLabel 
    - id_p : JLabel
    - addComponentButton : JButton 
    - addPilotButton : JButton
    - insertVehicleButton : JButton
    - insertRequestButton : JButton
    - removeComponentButton : JButton
    - removePilotButton : JButton
    - visualTimePsButton : JButton
    - visualStatusComponentButton : JButton
    - imgVec : ImageIcon 
    - imgWllp1 : ImageIcon
    + MeccanicoView()
    + JButton getAddComponentButton()
    + JButton getAddPilotButton()
    + JLabel getId_p()
    + JButton getInsertRequestButton()
    + JButton getInsertVehicleButton() 
    + JButton getRemoveComponentButton()
    + JButton getRemovePilotButton()
    + JButton getVisualStatusComponentButton()
    + JButton getVisualTimePsButton()
    + void setId_p()
  } 

  class StGraphicDetailsView{
    - frame : JFrame
    - mainPanel : JPanel
    - panel : JScrollPane
    - table : JTable
    + StGraphicDetailsView(Set<Components> components)
    + void show()
  }

  class StPopUpCreateStrategyView{
    - frame : JFrame
    - mainContainer : JPanel 
    - componentPanel : JPanel
    - strategyPanel : JPanel
    - mexPanel : JPanel
    - detailsButton : JButton  
    - box : JComboBox<String>
    - componentLabel1 : JLabel 
    - componentLabel2 : JLabel
    - strategyLabel1 : JLabel
    - strategyLabel2 : JLabel
    - strategyLabel3 : JLabel
    - mexLabel : JLabel
    - placeholder : JTextField
    + StPopUpCreateStrategyView()
    + JComboBox<String> getBox()
    + JLabel getComponentLabel1()
    + JLabel getComponentLabel2()
    + JPanel getComponentPanel()
    + JButton getDetailsButton()
    + JLabel getMexLabel()
    + JPanel getMexPanel()
    + JLabel getStrategyLabel2()
    + JPanel getStrategyPanel() 
    + void setBox(JComboBox<String> box) 
    + void setComponentLabel1(JLabel componentLabel1)
    + void setComponentLabel2(JLabel componentLabel2)
    + void setComponentPanel(JPanel componentPanel)
    + void setDetailsButton(JButton detailsButton)
    + void setMexLabel(JLabel mexLabel)
    + void setMexPanel(JPanel mexPanel)
    + void setStrategyLabel2(JLabel strategyLabel2)
    + void setStrategyPanel(JPanel strategyPanel)
    + void show() 
  }

  class StrategistView{
    - frame : JFrame 
    - mainContainer : JPanel 
    - titlePanel : JPanel
    - lapPanel : JPanel
    - timePanel : JPanel
    - buttonPanel : JPanel
    - getTimeButton : JButton 
    - createStrategyButton : JButton
    - countLapLabel : JLabel 
    - imgWeatherLabel : JLabel
    - imgCircuitLabel : JLabel
    - dataLabel : JLabel
    - imgWeather : ImageIcon
    - imgCircuit : ImageIcon
    - tabTime : DefaultTableModel 
    - tab : JTable
    + StrategistView()
    + void addRow(String t1, String t2, String t3, String t4)
    + void colorCell(int thresholdSector1, int thresholdSector2, int thresholdSector3)
    + JLabel getCountLapLabel()
    + JButton getCreateStrategyButton()
    + JButton getGetTimeButton()
    + JTable getTab()
    + void setCountLapLabel(JLabel countLapLabel)
    + void setCreateStrategyButton(JButton createStrategyButton)
    + void setGetTimeButton(JButton getTimeButton)
    + void setTab(JTable tab)
    }

  class WhPopUpDeleteRequestView{
    - frame : JFrame
    - dataPanel : JPanel 
    - sendPanel : JPanel
    - titleLabel : JLabel 
    - mexLabel : JLabel 
    - id_s : JTextField
    - id_c : JTextField
    - id_v : JTextField 
    - sendButton : JButton
    + WhPopUpDeleteRequestView()
    + void clearComponents(JPanel panel) 
    + JPanel getDataPanel() 
    + JTextField getId_c()
    + JTextField getId_s()
    + JTextField getId_v()
    + JButton getSendButton()
    + JPanel getSendPanel()
    + void mex1() 
    + void mex2()
    + JPanel setDataPanel() 
    + JTextField setId_c()
    + JTextField setId_s()
    + JTextField setId_v()
    + JButton setSendButton()
    + JPanel setSendPanel()
    + void show()
  }

  class WhPopUpShowRequestView{
    - frame : JFrame
    - mex : JPanel
    - text: JLabel
    - dataLabel : JLabel
    + WhPopUpShowRequestView(Set<Request> request)
    + void show()
  }

  class WhPopUpUpdateComponentView{
    - frame : JFrame
    - dataPanel : JPanel 
    - sendPanel : JPanel
    - titleLabel : JLabel 
    - mexLabel : JLabel 
    - id_c : JTextField
    - wear : JTextField
    - status : JTextField 
    - sendButton : JButton
    + hPopUpUpdateComponentView()
    + void clearComponents(JPanel panel)
    + JPanel getDataPanel()
    + JTextField getId_c()
    + JButton getSendButton()
    + JPanel getSendPanel()
    + JTextField getStatus()
    + JTextField getWear()
    + void mex1() 
    + void mex2() 
    + JPanel SetDataPanel()
    + JTextField setId_c()
    + JButton setSendButton()
    + JPanel setSendPanel()
    + JTextField setStatus()
    + JTextField setWear()
    + void show()
  }

  AbsController --o AbsView

  LoginController -- LoginView
  MagazziniereController -- MagazziniereView
  MeccanicoController -- MeccanicoView
  StrategistController -- StrategistView 

  LoginView --|> AbsView
  MagazziniereView --|> AbsView
  MeccanicoView --|> AbsView
  StrategistView --|> AbsView

  MagazziniereView -.|> Observer

  StPopUpCreateStrategyHandler -- StPopUpCreateStrategyView
  StPopUpCreateStrategyHandler -- StGraphicDetailsView
  WhPopUpDeleteRequestHandler -- WhPopUpDeleteRequestView
  WhPopUpShowRequestHandler -- WhPopUpShowRequestView
  WhPopUpUpdateComponentHandler -- WhPopUpUpdateComponentView
  McGraphicAllComponentHandler -- McGraphicAllComponentView
  McGraphicTimePsHandler -- McGraphicTimePsView
  McPopUpComponentHandler -- McPopUpComponentView
  McPopUpComponentHandler -- McPopUpRequestView
  McPopUpPilotHandler -- McPopUpPilotView
  McPopUpRequestHandler -- McPopUpRequestView
  McPopUpVehicleHandler -- McPopUpVehicleView
}

AbsView --|> JPanel

package frame{
  class Frame{
    - currentView : AbsView
    + Frame(int w, int h)
    + Dimension getCurrentSize()
    + void loadView(AbsView v)
  }

  Frame --o AbsView
  ControllerManager -up-o Frame
}

Frame -up-|> JFrame

package DAO{
  class DAOFactory << (S,Violet) singleton >>{
    - {static} DAOFactory instance 
    - DbType dbType
    - DAOFactory(DbType dbType)
    + {static} void createInstance (DbType  dbType)
    + {static} UserDAO createUserDAO() 
  }

  enum DbType {
    MYSQL
  }
}

package DAO.mysql{
  class DBConnection{
    - {static} String PROPERTYDBDRIVER
    - {static} String PROPERTYDBURL
    - {static} String dbDriver 
    - {static} String dbURL 
    - {static} boolean isInit 
    - Connection conn
    - static void init()
    + DBConnection(String schema)
    + void close()
    + Connection getConnection()
    + boolean isOpen() 
  }
  
  class MagazziniereDAO{
    - String SCHEMA
    + void checkCompo(String id_c)
    + void checkRequest(String id_s, String id_c, String id_v)
    + int countElement()
    + int countElementBySelect(String select)
    + void  insertLogEvent(String id_staff, String desc)
    + void removeRequest(String idc)
    + Set<Request> selectAllRequest()
    + boolean updateComponent(String id, String wear, String status
  }

  class MeccanicoDAO{
    - String SCHEMA
    + void checkCompo(String id_c, String name, String status)
    + void checkIdCompo(String id_c)
    + void checkPilot(String id_p)
    + boolean checkPilotOnVehicle(String idp)
    + void checkRequest(String id_c)
    + void checkStaff(String id)
    + void checkVehicle(String msn)
    + boolean insertComponent(String id, String msn)
    + void  insertLogEvent(String id_staff, String desc)
    + boolean insertMeccOnVehicle(String msn, String id)
    + boolean insertPilotOnVehicle(String id_p, String msn)
    + boolean insertRequest(String desc, String id_s, String id_c, String id_v)
    + void removeComponent(String id_c, String id_v)
    + boolean removePilot(String idp)
    + void selectP(String id, String name, String surname, String number)
    + boolean updateWear(int wear, String id)
  }

  class StrategistDAO {
    - {static} String SCHEMA
    + void  insertLogEvent(String id_staff, String desc)
  }

  class UserDAO {
    - {static} String SCHEMA
    + {static} TypeController selectByIDandPwd(String id, String pwd)
    + Staff selectById(String id)
  }
  
  class VehicleDAO {
    - {static} String SCHEMA
    + boolean timeSector(Vehicle v)
  }
}

DAOFactory -* DbType
DBConnection -up.|> AutoClosable
ControllerManager -- DAOFactory

Session -- MagazziniereDAO

MagazziniereDAO -- WhPopUpUpdateComponentHandler
MagazziniereDAO -- WhPopUpDeleteRequestHandler

MeccanicoDAO -- McPopUpPilotHandler
MeccanicoDAO -- McPopUpVehicleHandler
MeccanicoDAO -- McPopUpRequestHandler
MeccanicoDAO -- McPopUpComponentHandler

StrategistDAO -- StPopUpCreateStrategyHandler
VehicleDAO -- StrategistController

@enduml